FROM golang:1.18-alpine

  # Install git
RUN set -ex; \
apk update; \
apk add --no-cache git

  # Set working directory
WORKDIR /go/src/github.com/pennsieve/publishing-service/lambda/service

  # Run tests
RUN pwd
RUN ls -l
RUN find .
CMD CGO_ENABLED=0 go test -v ./...
